package domains.user.http

import domains.user.http.mapper.UserHttpResponseMappers



import domains.user.http.UserHttpPlanRegistry.RegisteredPlan.{AuthenticatedPlain, AuthenticatedWithTransaction, SiteManagerPlain, SiteManagerWithTransaction}

object UserHttpPlanDefinitions:

  val listUsers = SiteManagerPlain(UserHttpPlans.ListUsers, UserHttpResponseMappers.listUsersResponse)
  val listUserSuggestions = AuthenticatedPlain(UserHttpPlans.ListUserSuggestions, UserHttpResponseMappers.listUserSuggestionsResponse)
  val getUserProfile = AuthenticatedPlain(UserHttpPlans.GetUserProfile, UserHttpResponseMappers.mapGetUserProfileResult)
  val getUserSettings = AuthenticatedPlain(UserHttpPlans.GetUserSettings, UserHttpResponseMappers.mapGetUserSettingsResult)
  val listContributionRanklist = AuthenticatedPlain(UserHttpPlans.ListContributionRanklist, UserHttpResponseMappers.listContributionRanklistResponse)
  val listAcceptedRanklist = AuthenticatedPlain(UserHttpPlans.ListAcceptedRanklist, UserHttpResponseMappers.listAcceptedRanklistResponse)
  val updateUserPermissions = SiteManagerWithTransaction(UserHttpPlans.UpdateUserPermissions, UserHttpResponseMappers.mapUpdateUserPermissionsResult)
  val updateOwnProfile = AuthenticatedWithTransaction(UserHttpPlans.UpdateOwnProfile, UserHttpResponseMappers.mapUpdateUserSettingsOutput)
  val updateOwnPreferences = AuthenticatedWithTransaction(UserHttpPlans.UpdateOwnPreferences, UserHttpResponseMappers.mapUpdateUserSettingsOutput)
  val updateOwnAccount = AuthenticatedWithTransaction(UserHttpPlans.UpdateOwnAccount, UserHttpResponseMappers.mapUpdateUserSettingsOutput)
  val updateManagedProfile = SiteManagerWithTransaction(UserHttpPlans.UpdateManagedProfile, UserHttpResponseMappers.mapUpdateUserSettingsOutput)
  val updateManagedPreferences = SiteManagerWithTransaction(UserHttpPlans.UpdateManagedPreferences, UserHttpResponseMappers.mapUpdateUserSettingsOutput)
  val updateManagedAccount = SiteManagerWithTransaction(UserHttpPlans.UpdateManagedAccount, UserHttpResponseMappers.mapUpdateUserSettingsOutput)
  val deleteUser = SiteManagerWithTransaction(UserHttpPlans.DeleteUser, UserHttpResponseMappers.mapDeleteUserResult)
